### ISSUE TITLE
[FEATURE] Group conversion pairings

### ISSUE THREAD

**Issue by jeroenptrs** [CityOfZion/neo-toolbox#1]
Well this is more of a discussion than issue, but we should look for the best way to group conversions. Should we auto detect and filter based on what has been entered? (I'm a big fan of that).

I'd really like for us to handle things intuitively, but with minimal effort for the user. This is why I really liked @metachris' idea of detecting input and filtering onwards. I do like the way the account setup @snowypowers added right now works and is a great example of what I'm trying to bring across.

All of this can work **really well** with the design I suggested as well too! 😆 

Known conversions:
* [x] reversehex string (already implemented)
* [x] number <-> fixed8 (already implemented)
* [x] Pubkey -> address (implemented under account)
* [x] wif <-> privkey (implemented under account)
* [x] privkey/wif -> pubkey/address (implemented under account)
* [x] scripthash <-> address [implemented under account] ([from neo-python-core](https://github.com/CityOfZion/neo-python-core/issues/39))
* [x] bytearray <-> string/int ([from neo-python-core](https://github.com/CityOfZion/neo-python-core/issues/39))
* [x] hexstring <-> string/int ([from neo-python-core](https://github.com/CityOfZion/neo-python-core/issues/39))
* [x] hex encode/decode <-> bytearray ([from neo-python-core](https://github.com/CityOfZion/neo-python-core/issues/39))
